name: Super-Linter
on: push
jobs:
  super-lint: 
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout

      - name: Run Super-linter
        uses: github/super-linter
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
